version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  tests:
    build: .
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app

volumes:
  db_data:
