

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./tmp:/tmp     
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: >
      sh -c "pytest -v db_tests.py --junitxml=/tmp/report.xml"

volumes:
  db_data: