"""
Написати 25 XPath та 25 CSS локаторів для сайту https://qauto2.forstudy.space/
"""

username = "guest"
passwd = "welcome2qauto"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

class Locators:
    # XPath Locators
    HEADER_LOGO_XPATH = "//a[@class='header_logo']"
    MODAL_WINDOW_XPATH = "//div[contains(@class, 'modal-content')]"
    MODAL_TITLE_XPATH = "//h4[@class='modal-title']"
    MODAL_CLOSE_BUTTON_XPATH = "//button[@class='close']"
    FORM_LOGIN_XPATH = "//form[@id='signin-form']"
    FORM_SIGNUP_XPATH = "//form[@id='signup-form']"
    INPUT_EMAIL_XPATH = "//input[@placeholder='Email']"
    INPUT_PASSWORD_XPATH = "//input[@placeholder='Password']"
    INPUT_NAME_XPATH = "//input[@placeholder='Name']"
    INPUT_LASTNAME_XPATH = "//input[@placeholder='Last Name']"
    DROPDOWN_CAR_BRAND_XPATH = "//select[@formcontrolname='carBrandId']"
    DROPDOWN_CAR_MODEL_XPATH = "//select[@formcontrolname='carModelId']"
    INPUT_LICENSE_PLATE_XPATH = "//input[@placeholder='License plate']"
    INPUT_MILEAGE_XPATH = "//input[@placeholder='Mileage']"
    BUTTON_ADD_CAR_XPATH = "//button[contains(text(), 'Add car')]"
    SIDEBAR_MENU_XPATH = "//aside[contains(@class, 'sidebar')]"
    SIDEBAR_DASHBOARD_XPATH = "//a[contains(text(), 'Dashboard')]"
    SIDEBAR_CARS_XPATH = "//a[contains(text(), 'Cars')]"
    SIDEBAR_SETTINGS_XPATH = "//a[contains(text(), 'Settings')]"
    DASHBOARD_HEADER_XPATH = "//h2[contains(text(), 'Dashboard')]"
    DASHBOARD_CARD_TITLE_XPATH = "//div[@class='dashboard_card']//h5"
    TOAST_NOTIFICATION_XPATH = "//div[contains(@class, 'toast-message')]"
    LOADER_SPINNER_XPATH = "//div[contains(@class, 'spinner-border')]"
    ERROR_TEXT_XPATH = "//small[contains(@class, 'text-danger')]"
    CHECKBOX_TERMS_XPATH = "//input[@type='checkbox']"

    # CSS Locators
    HEADER_LOGO_CSS = "a.header_logo"
    MODAL_WINDOW_CSS = "div.modal-content"
    MODAL_TITLE_CSS = "h4.modal-title"
    MODAL_CLOSE_BUTTON_CSS = "button.close"
    FORM_LOGIN_CSS = "form#signin-form"
    FORM_SIGNUP_CSS = "form#signup-form"
    INPUT_EMAIL_CSS = "input[placeholder='Email']"
    INPUT_PASSWORD_CSS = "input[placeholder='Password']"
    INPUT_NAME_CSS = "input[placeholder='Name']"
    INPUT_LASTNAME_CSS = "input[placeholder='Last Name']"
    DROPDOWN_CAR_BRAND_CSS = "select[formcontrolname='carBrandId']"
    DROPDOWN_CAR_MODEL_CSS = "select[formcontrolname='carModelId']"
    INPUT_LICENSE_PLATE_CSS = "input[placeholder='License plate']"
    INPUT_MILEAGE_CSS = "input[placeholder='Mileage']"
    BUTTON_ADD_CAR_CSS = "button:contains('Add car')"  # Note: ":contains" is not standard CSS, only usable in jQuery
    SIDEBAR_MENU_CSS = "aside.sidebar"
    SIDEBAR_DASHBOARD_CSS = "a:contains('Dashboard')"
    SIDEBAR_CARS_CSS = "a:contains('Cars')"
    SIDEBAR_SETTINGS_CSS = "a:contains('Settings')"
    DASHBOARD_HEADER_CSS = "h2:contains('Dashboard')"
    DASHBOARD_CARD_TITLE_CSS = "div.dashboard_card h5"
    TOAST_NOTIFICATION_CSS = "div.toast-message"
    LOADER_SPINNER_CSS = "div.spinner-border"
    ERROR_TEXT_CSS = "small.text-danger"
    CHECKBOX_TERMS_CSS = "input[type='checkbox']"
