XPATH_LOCATORS = {
    "sign_in_button": "//button[text()='Sign In']",
    "email_input": "//input[@placeholder='Email']",
    "password_input": "//input[@placeholder='Password']",
    "main_heading": "//h1[contains(text(),'Welcome')]",
    "garage_nav": "//a[@href='/garage' and text()='Garage']",
    "home_nav": "//nav//li/a[text()='Home']",
    "garage_container": "//div[contains(@class,'garage')]",
    "user_menu": "//div[@id='userMenu']",
    "submit_button": "//form//button[@type='submit']",
    "car_table_brand": "//table//th[text()='Brand']",
    "first_car_brand": "//table//tr[1]/td[2]",
    "car_card": "//div[contains(@class,'car__card')]",
    "modal_close": "//div[@class='modal']//button[contains(@class,'close')]",
    "logout_span": "//span[text()='Logout']",
    "first_name_input": "//label[text()='First name']/following-sibling::input",
    "checkbox": "//input[@type='checkbox' and @name='agreement']",
    "car_brand_select": "//select[@name='carBrand']",
    "car_model_select": "//select[@name='carModel']",
    "mileage_input": "//input[@name='carMileage']",
    "add_car_button": "//button[contains(text(),'Add car')]",
    "no_cars_msg": "//div[contains(text(),'No cars')]",
    "number_input": "//input[@type='number']",
    "privacy_footer": "//footer//a[contains(text(),'Privacy')]",
    "cancel_button": "//button[normalize-space()='Cancel']",
    "dropdown_links": "//div[@class='dropdown-menu']//a"
}

CSS_LOCATORS = {
    "sign_in_button": "button[type='submit']",
    "email_input": "input[placeholder='Email']",
    "password_input": "input[placeholder='Password']",
    "main_heading": "h1.title",
    "garage_nav": "a[href='/garage']",
    "home_nav": "nav li a[href='/']",
    "garage_container": "div.garage",
    "user_menu": "#userMenu",
    "submit_button": "form button[type='submit']",
    "car_table_brand": "table th:nth-child(2)",
    "first_car_brand": "table tr:first-child td:nth-child(2)",
    "car_card": ".car__card",
    "modal_close": ".modal button.close",
    "logout_span": "span.logout",
    "first_name_input": "label[for='firstName'] + input",
    "checkbox": "input[type='checkbox'][name='agreement']",
    "car_brand_select": "select[name='carBrand']",
    "car_model_select": "select[name='carModel']",
    "mileage_input": "input[name='carMileage']",
    "add_car_button": "button.add-car",
    "no_cars_msg": "div.no-cars",
    "number_input": "input[type='number']",
    "privacy_footer": "footer a[href*='privacy']",
    "cancel_button": "button.cancel-button",
    "dropdown_links": ".dropdown-menu a"
}