version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DB_HOST: postgres_db
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "homework_29.py"]


volumes:
  postgres_data: