"""
Написати 25 XPath та 25 CSS локаторів для сайту https://qauto2.forstudy.space/
"""

username = "guest"
passwd = "welcome2qauto"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

#XPath
HOME_MENU_BUTTON_XPATH = "//a[text()="Home"]"
ABOUT_MENU_BUTTON_XPATH = "//button[@appscrollto="aboutSection" or text()="About"]"
CONTACTS_MENU_BUTTON_XPATH = "//button[@appscrollto="contactsSection" or text()="Contacts"]"
GUEST_LOG_IN_BUTTON_XPATH = "//button[@class="header-link -guest"]"
SIGN_IN_BUTTON_XPATH = "//button[@class="btn btn-outline-white header_signin" or text()="Sign in"]"
SIGN_IN_EMAIL_FIELD_XPATH = "//input[@id="signinEmail"]"
SIGN_IN_REMEMBER_ME_CHECKBOX_XPATH = "//input[@id="remember" and @type="checkbox"]"
SIGN_IN_FORGOT_PASSWORD_XPATH = "//button[@class="btn btn-link" and text()="Forgot password"]"
SIGN_IN_REGISTRATION_XPATH = "//button[@class="btn btn-link" and text()="Registration"]"
SIGN_IN_CLOSE_ICON_XPATH = "//button[@class="close"]//span"
SIGN_UP_BUTTON_XPATH = "//button[@class="hero-descriptor_btn btn btn-primary" or text()="Sign up"]"
PLAY_PLAYER_BUTTON_XPATH = "//div[@class= "ytp-cued-thumbnail-overlay"]//child::button"
WATCH_LATER_PLAYER_BUTTON_XPATH = "//button[@title="Watch later"]"
SHARE_PLAYER_BUTTON_XPATH = "//button[@aria-label="Share"]"
SHARE_LINK_XPATH = "//a[@title="Share link"]"
SHARE_FACEBOOK_XPATH = "//a[@title="Facebook"]"
SHARE_X_XPATH = "//a[@title="X"]"
SHARE_MORE_ELIPSES_XPATH = "//a[@title="More"]"
CLOSE_SHARE_ICON_XPATH = "//button[@class="ytp-share-panel-close ytp-button"]"
NAV_TO_YOUTUBE_FROM_TITLE_XPATH = "//a[contains(@href, "https://www.youtube.com") and @class="ytp-title-link yt-uix-sessionlink"]"
NAV_TO_YOUTUBE_FROM_WATERMARK_XPATH = "//a[contains(@href, "https://www.youtube.com") and @class="ytp-watermark yt-uix-sessionlink"]"
NAV_TO_HILLEL_XPATH = "//a[@href="https://ithillel.ua" and text()="ithillel.ua"]"
MAIL_TO_HILLEL_XPATH = "//a[@href="mailto:developer@ithillel.ua" and text()="support@ithillel.ua"]"
CONTACT_NAV_TO_LINKEDIN_XPATH = "//span[@class="socials_icon icon icon-linkedin"]"
CONTACT_NAV_TO_TELEGRAM_XPATH = "//a[@href="https://t.me/ithillel_kyiv"]//span"

#CSS
HOME_MENU_BUTTON_CSS = "a.btn.header-link.-active"
ABOUT_MENU_BUTTON_CSS = "button[appscrollto="aboutSection"]"
CONTACTS_MENU_BUTTON_CSS = "button[appscrollto="contactsSection"]"
GUEST_LOG_IN_BUTTON_CSS = "button.header-link.-guest"
SIGN_IN_BUTTON_CSS = "button.btn.btn-outline-white.header_signin"
SIGN_IN_EMAIL_FIELD_CSS = "input#signinEmail"
SIGN_IN_REMEMBER_ME_CHECKBOX_CSS = "input#remember"
SIGN_IN_FORGOT_PASSWORD_CSS = "button.btn.btn-link"
SIGN_IN_REGISTRATION_CSS = "button.btn.btn-link[type="button"]"
SIGN_IN_CLOSE_ICON_CSS = "button.close span"
SIGN_UP_BUTTON_CSS = "button.hero-descriptor_btn.btn.btn-primary"
PLAY_PLAYER_BUTTON_CSS = "button.ytp-large-play-button.ytp-button.ytp-large-play-button-red-bg"
WATCH_LATER_PLAYER_BUTTON_CSS = "button.ytp-watch-later-button.ytp-button.ytp-show-watch-later-title"
SHARE_PLAYER_BUTTON_CSS = "button.ytp-button.ytp-share-button.ytp-show-share-title.ytp-share-button-visible"
SHARE_LINK_CSS = "a.ytp-share-panel-link.ytp-no-contextmenu"
SHARE_FACEBOOK_CSS = "a[title="Facebook"]"
SHARE_X_CSS = "a[title="X"]"
SHARE_MORE_ELIPSES_CSS = "a[title="More"]"
CLOSE_SHARE_ICON_CSS = "button.ytp-share-panel-close.ytp-button"
NAV_TO_YOUTUBE_FROM_TITLE_CSS = "a.ytp-title-link.yt-uix-sessionlink"
NAV_TO_YOUTUBE_FROM_WATERMARK_CSS = "a.ytp-watermark.yt-uix-sessionlink"
NAV_TO_HILLEL_CSS = "a.contacts_link.display-4"
MAIL_TO_HILLEL_CSS = "a.contacts_link.h4"
CONTACT_NAV_TO_LINKEDIN_CSS = "span.socials_icon.icon.icon-linkedin"
CONTACT_NAV_TO_TELEGRAM_CSS = "a[href="https://t.me/ithillel_kyiv"] span"