"""
Написати 25 XPath та 25 CSS локаторів для сайту https://qauto2.forstudy.space/
"""

username = "guest"
passwd = "welcome2qauto"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

class Locators:
    H1_XPATH = "//h1[contains(text(), 'Do more!')]"
    MAIN_TEXT_XPATH = "//p[contains(text(), 'With the help of the Hillel auto project')]"
    BUTTON_SIGN_UP_XPATH = "//button[contains(text(), 'Sign up')]"
    BUTTON_SIGN_IN_XPATH = "//button[@class='btn btn-outline-white header_signin']"
    BUTTON_GUEST_LOG_IN_XPATH = "//button[@class='header-link -guest']"
    NAVIGATION_HOME_XPATH = "//a[contains(text(), 'Home')]"
    NAVIGATION_ABOUT_XPATH = "//button[contains(text(), 'About')]"
    NAVIGATION_CONTACTS_XPATH = "//button[contains(text(), 'Contacts')]"
    NAVIGATION_GUEST_LOGIN_XPATH = "//button[contains(text(), 'Guest log in')]"
    NAVIGATION_SIGN_IN_XPATH = "//button[contains(text(), 'Sign In')]"
    IMG_FUEL_EXPERIENCE_XPATH = "//div[@class='col-12 col-lg-6']//img[@alt='Instructions']"
    IMG_INSTRUCTIONS_XPATH = "//div[@class='col-12 col-lg-6 mt-lg-0 mt-md-5 mt-sm-4 mt-3']//img[@alt='Instructions']"
    IFRAME_XPATH = "//iframe[contains(@class, 'hero-video_frame')]"
    CONTACTS_XPATH = "//h2[contains(text(), 'Contacts')]"
    FACEBOOK_XPATH = "//a[contains(@href, 'https://www.facebook.com')]"
    TELEGRAM_XPATH = "//a[contains(@href, 'https://t.me/')]"
    YOUTUBE_XPATH = "//a[contains(@href, 'https://www.youtube.com')]"
    INSTAGRAM_XPATH = "//a[contains(@href, 'https://www.instagram.com')]"
    LINKEDIN_XPATH = "//a[contains(@href, 'https://www.linkedin.com')]"
    EMAIL_XPATH = "//a[@href='mailto:developer@ithillel.ua']"
    LINK_MAIN_XPATH = "//a[contains(@href, 'https://ithillel.ua/')]"
    FOOTER_LEFT_XPATH = "//p[contains(text(), '© 2021 Hillel IT school')]/parent::div"
    FOOTER_RIGHT_XPATH = "//div[@class='col footer_item -right']"
    FOOTER_TEXT_YEAR_XPATH = "//p[contains(text(), '© 2021 Hillel IT school')]"
    FOOTER_TEXT_XPATH = "// p[contains(text(), 'Hillel auto developed in Hillel IT school for educ')]"
    FOOTER_LOGO_XPATH = "//a[contains(@class, 'footer_logo')]"

    H1_CSS = "h1"
    BUTTON_SIGN_UP_CSS = "button:contains('Sign up')"
    BUTTON_SIGN_IN_CSS = "button.btn.btn-outline-white.header_signin"
    BUTTON_GUEST_LOG_IN_CSS = "button.header-link.-guest"
    NAVIGATION_HOME_CSS = "a:contains('Home')"
    NAVIGATION_ABOUT_CSS = "button:contains('About')"
    NAVIGATION_CONTACTS_CSS = "button:contains('Contacts')"
    NAVIGATION_GUEST_LOGIN_CSS = "button:contains('Guest log in')"
    NAVIGATION_SIGN_IN_CSS = "button:contains('Sign In')"
    IMG_FUEL_EXPERIENCE_CSS = "div.col-12.col-lg-6 img[alt='Instructions']"
    IMG_INSTRUCTIONS_CSS = "div.col-12.col-lg-6.mt-lg-0.mt-md-5.mt-sm-4.mt-3 img[alt='Instructions']"
    IFRAME_CSS = "iframe.hero-video_frame"
    CONTACTS_CSS = "h2:contains('Contacts')"
    FACEBOOK_CSS = "a[href*='facebook.com']"
    TELEGRAM_CSS = "a[href*='t.me']"
    YOUTUBE_CSS = "a[href*='youtube.com']"
    INSTAGRAM_CSS = "a[href*='instagram.com']"
    LINKEDIN_CSS = "a[href*='linkedin.com']"
    EMAIL_CSS = "a[href='mailto:developer@ithillel.ua']"
    LINK_MAIN_CSS = "a[href*='ithillel.ua']"
    FOOTER_LEFT_CSS = "p:contains('© 2021 Hillel IT school')"
    FOOTER_RIGHT_CSS = "div.col.footer_item.-right"
    FOOTER_TEXT_YEAR_CSS = "p:contains('© 2021 Hillel IT school')"
    FOOTER_TEXT_CSS = "p:contains('Hillel auto developed in Hillel IT school for educ')"
    FOOTER_LOGO_CSS = "a.footer_logo"
